apiVersion: v1
kind: Service
metadata:
  name: rails-backend
  namespace: neighborly
labels:
  app: rails-backend
spec:
  clusterIP: None
  selector:
    app: rails-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
