apiVersion: v1
kind: Service
metadata:
  name: rails-backend
  namespace: library
  labels:
    app: rails-backend
spec:
  clusterIP: None
  selector:
    app: rails-backend
  ports:
    - name: http
      port: 80
      targetPort: 80
