{{- if .Values.frontend.static.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-static
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: neighborly-library
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
data:
  index.html: |-
{{ .Files.Get "files/frontend/index.html" | indent 4 }}
  app.js: |-
{{ .Files.Get "files/frontend/app.js" | indent 4 }}
  styles.css: |-
{{ .Files.Get "files/frontend/styles.css" | indent 4 }}
{{- end }}
